import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/app/components/layout/Header'
import Footer from './components/layout/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dine Market',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className='px-8' >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
